apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter
  namespace: tfm
spec:
  storageClassName: jupyter
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  hostPath:
    path: /data/jupyter/
