apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jupyter
  namespace: tfm
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate