apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterlab-pvc
  namespace: tfm
spec:
  storageClassName: jupyter
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
