apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: minikube-ingress
  namespace: tfm
  annotations:
spec:
  rules:
  - host: kubernetes-tfm
    http:
      paths:
      - path: /
        backend:
          serviceName: web-service
          servicePort: 3000
      - path: /spark
        backend:
          serviceName: spark-master
          servicePort: 8080
      - path: /jupyter
        backend:
          serviceName: jupyterlab
          servicePort: 80
      - path: /mongo
        backend:
          serviceName: mongo-express-service
          servicePort: 8081
      - path: /orion
        backend:
          serviceName: orion
          servicePort: 1026
