apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-pv
  namespace: tfm
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 30Gi
  hostPath:
    path: /data/spark/
